version: '3.9'

services:

        app:
                image: nginx:latest
                volumes:
                        - .:/var/www/html

        elbe:
                image: nginx:latest
                volumes:
                        - ./conf.d:/etc/nginx/conf.d
                depends_on:
                        - api
                ports:
                        - 85:3000
